env: local

db_url: "postgres://user:password@localhost:5432/news_service?sslmode=disable"

http:
  port: 8080
  host: localhost
  read_timeout: 10s
  write_timeout: 10s

redis:
  host: localhost
  port: 6379
  password: password
  db: 0
  cache_ttl: 5m
