env: local

db_url: "postgres://user:password@postgres:5432/news_service?sslmode=disable"

http:
  port: 8080
  host: 0.0.0.0
  read_timeout: 10s
  write_timeout: 10s

redis:
  host: news_redis
  port: 6379
  password: ""
  db: 0
  cache_ttl: 5m
