
services:
  news-service:
    build: .
    container_name: news_app
    environment:
      - DB_URL=postgres://user:password@postgres:5432/news_service?sslmode=disable
    ports:
      - "8080:8080"
    depends_on: 
      postgres:
        condition: service_healthy 
      redis:
        condition: service_started
    restart: unless-stopped


  postgres:
    image: postgres:15-alpine
    container_name: news_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: news_service
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db-for-tests.sh:/docker-entrypoint-initdb.d/init-db-for-tests.sh

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d news_service"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    
  redis:
    image: redis:7-alpine
    container_name: news_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  postgres_data:

  redis_data: 