name: CI

on:
  push:
    branches: [main,dev]
  pull_request:
    branches: [main,dev]

  
jobs:
  go-lint:
    name: Go lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          cache: false

      - name: Install dependencies
        run: make go-deps

      - name: Run golangci-lint
        run: make go-lint
  
  tests:
    name: Go tests
    needs: go-lint
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: news_service_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install goose
        run: go install github.com/pressly/goose/v3/cmd/goose@latest

      - name: Run migrations on test DB
        env:
          GOOSE_DRIVER: postgres
          GOOSE_DBSTRING: "postgres://user:password@localhost:5432/news_service_test?sslmode=disable"
        run: goose -dir ./src/news/migrations/postgres up

      - name: Run Go tests
        env:
          DB_URL_TEST: "postgres://user:password@localhost:5432/news_service_test?sslmode=disable"
        run: go test -v -race ./...